"""
BU YERDA SIZGA KERAKLI BO'LADIGAN TOKEN VA SHUNGA O'XSHAGAN MA'LUMOTLAR SAQLANADI
"""
from settings import *
TOKEN = TOKEN
PROVIDER_TOKEN = PROVIDER_TOKEN
ADMINS = ''''''

DB_NAME = DATABASE_NAME
DB_HOST = DATABASE_HOST
DB_PASSWORD = DATABASE_PASSWORD
DB_PORT = DATABASE_PORT
DB_USER = DATABASE_USER


